#!/usr/bin/env node
const fs = require("fs");
const path = require("path");

const root = path.resolve(process.argv[2] || process.cwd());
const exportDir = path.join(root, "kb", "11_import_export", "export");
const entitiesPath = path.join(exportDir, "all_entities.json");
const reportPath = path.join(root, "COVERAGE_MATRIX.md");

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function countBy(values) {
  return [...values].sort().reduce((acc, value) => {
    acc[value] = (acc[value] || 0) + 1;
    return acc;
  }, {});
}

const allEntities = readJson(entitiesPath);
const entities = allEntities.entities || [];
const byType = countBy(entities.map((entity) => entity.entity_type));
const phaseCounts = countBy(entities.flatMap((entity) => entity.phase_groups || []));
const domainCounts = countBy(entities.flatMap((entity) => entity.domains || []));

const lines = [
  "# Coverage Matrix",
  "",
  "Generated by `npm run kb:coverage`.",
  "",
  "## Summary",
  "",
  `- schema_version: \`${allEntities.schema_version}\``,
  `- entities: ${entities.length}`,
  `- generated_at: ${new Date().toISOString()}`,
  "",
  "## Entity Type Coverage",
  "",
  "| Entity Type | Count |",
  "|---|---:|",
  ...Object.entries(byType).map(([key, value]) => `| ${key} | ${value} |`),
  "",
  "## Phase Coverage",
  "",
  "| Phase Group | Count |",
  "|---|---:|",
  ...Object.entries(phaseCounts).map(([key, value]) => `| ${key} | ${value} |`),
  "",
  "## Domain Coverage",
  "",
  "| Domain | Count |",
  "|---|---:|",
  ...Object.entries(domainCounts).map(([key, value]) => `| ${key} | ${value} |`),
  "",
  "## Gate",
  "",
  "Coverage quantity is adequate for the draft KB release. Verified source-backed release remains blocked until legal/user evidence exists."
];

fs.writeFileSync(reportPath, `${lines.join("\n")}\n`, "utf8");
console.log(`coverage summary written: ${reportPath}`);
