#!/usr/bin/env node
const fs = require("fs");
const path = require("path");

const root = path.resolve(process.argv[2] || process.cwd());
const sourcesPath = path.join(root, "kb", "01_sources", "sources.json");
const searchPath = path.join(root, "kb", "11_import_export", "export", "search_index.json");
const reportPath = path.join(root, "SOURCE_GOVERNANCE_AUDIT.md");

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

const sources = readJson(sourcesPath).source_documents || [];
const searchDocs = readJson(searchPath).documents || [];
const highRisk = sources.filter((source) => source.risk_level === "high" || source.source_origin_flags?.includes("HIGH_RISK_SOURCE"));
const unsafeHighRisk = highRisk.filter((source) => source.ingestion_status !== "metadata_only_quarantined");
const unsafeSearch = searchDocs.filter((doc) => {
  const metadataOnly = doc.source_basis === "metadata_only" || doc.status === "metadata_only_quarantined";
  const excerpt = String(doc.body_excerpt_safe || "");
  return metadataOnly && excerpt && !excerpt.startsWith("[suppressed") && !excerpt.startsWith("[not applicable");
});

const status = unsafeHighRisk.length || unsafeSearch.length ? "FAIL" : "PASS";
const lines = [
  "# Source Governance Audit",
  "",
  "Generated by `npm run kb:audit`.",
  "",
  `- status: ${status}`,
  `- generated_at: ${new Date().toISOString()}`,
  `- source_records: ${sources.length}`,
  `- high_risk_records: ${highRisk.length}`,
  `- unsafe_high_risk_records: ${unsafeHighRisk.length}`,
  `- unsafe_metadata_only_search_excerpts: ${unsafeSearch.length}`,
  "",
  "## Policy",
  "",
  "High-risk files remain metadata-only. `user_provided_file` does not imply legal permission for AI processing. Body extraction, summaries, long quotations, and embeddings are blocked unless a legal sidecar explicitly allows processing.",
  "",
  "## High-Risk Source Status",
  "",
  "| Source | Risk | Ingestion Status | Source Basis |",
  "|---|---|---|---|",
  ...highRisk.map((source) => `| ${source.source_document_id || source.id} | ${source.risk_level || "high"} | ${source.ingestion_status || ""} | ${source.source_basis || ""} |`),
  "",
  "## Result",
  "",
  status === "PASS"
    ? "No P0 source-governance violations detected."
    : "P0 source-governance violations detected. Repair before release."
];

fs.writeFileSync(reportPath, `${lines.join("\n")}\n`, "utf8");
console.log(`source governance audit written: ${reportPath}`);
if (status !== "PASS") {
  process.exitCode = 1;
}
